<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data =
        array(
            array('title' => 'Ananthapur','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Chittoor','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Madanapalle','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Kadapa','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Hindupur','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Dharmavaram','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Anantapur','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Kurnool','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Prakasam','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'West Godavari','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Palakol','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Vizianagaram','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Krishna','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Nellore','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Guntur','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Machilipatnam','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Avanigadda','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Warangal','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Kovvur','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'West Godavari','state_id' => '2','country_id' => '1','status' => '1'),
            array('title' => 'Tadepalligudem','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'East Godavari','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Bapatla','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Karim Nagar','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Amlapuram','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Visakhapatnam','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Yanam','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Srikakulam','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Vizianagaram','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Bhadrachalam','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Srikalahasti','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Bhongir','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Karimganj','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Hailakandi','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Cachar','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Dima Hasso - North Cachar Hill','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Karbi Anglong','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Udalguri','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Sonitpur','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Darrang','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Bongaigaon','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Kokrajhar','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Goalpara','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Dhubri','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Kamrup','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Kamrup Metropolitan','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Baksa','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Nalbari','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Barpeta','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Lakhimpur','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Dibrugarh','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Dhemaji','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Sonapur','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Marigaon','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Nagaon','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Sibsagar','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Golaghat','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Jorhat','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Tinsukia','state_id' => '4','country_id' => '1','status' => '1'),
            array('title' => 'Gaya','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Aurangabad','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Arwal','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Aurangabad','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Auranagabad','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Bhojpur','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Buxar','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Jehanabad','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Kaimur Bhabua','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Patna','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Jamui','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'East Champaran','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Purnia','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Rohtas','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Vaishali','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Samastipur','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Begusarai','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Khagaria','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Katihar','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Bhagalpur','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Banka','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Deoghar','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Banka','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Kishanganj','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Lakhisarai','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Munger','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Sheikhpura','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Nalanda','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Nawada','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Sheohar','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Madhepura','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Supaul','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Saharsa','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Darbhanga','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Muzaffarpur','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Darbhanga','state_id' => '8','country_id' => '1','status' => '1'),
            array('title' => 'Darbhanga','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Sitamarhi','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Darbhanga','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Madhubani','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Darbhanga','state_id' => '10','country_id' => '1','status' => '1'),
            array('title' => 'Darbhanga','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Darbhanga','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Darbhanga','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Darbhanga','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Darbhanga','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Na','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'West Champaran','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Araria','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Saran','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Gopalganj','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Siwan','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Bilaspurcgh','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Janjgirchampa','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Korba','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Mungeli','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Janjgir-champa','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Durg','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Rajnandgaon','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Balod','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Bemetara','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Kawardha','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Raigarh','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Surguja','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Jaspur','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Balrampur','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Koriya','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Surajpur','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Gariaband','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Mahasamund','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Dhamtari','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Raipur','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Balod Bazer','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Kanker','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Jagdalpur','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Bastar','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Dantewada','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Bijapur(cgh)','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Bilaspur','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Narayanpur','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Sukma','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Makdi','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'Kondagaon','state_id' => '16','country_id' => '1','status' => '1'),
            array('title' => 'East Delhi','state_id' => '17','country_id' => '1','status' => '1'),
            array('title' => 'Shahdara','state_id' => '17','country_id' => '1','status' => '1'),
            array('title' => 'North East Delhi','state_id' => '17','country_id' => '1','status' => '1'),
            array('title' => 'New Delhi','state_id' => '17','country_id' => '1','status' => '1'),
            array('title' => 'North Delhi','state_id' => '17','country_id' => '1','status' => '1'),
            array('title' => 'North West Delhi','state_id' => '17','country_id' => '1','status' => '1'),
            array('title' => 'Central Delhi','state_id' => '17','country_id' => '1','status' => '1'),
            array('title' => 'South Delhi','state_id' => '17','country_id' => '1','status' => '1'),
            array('title' => 'South West Delhi','state_id' => '17','country_id' => '1','status' => '1'),
            array('title' => 'West Delhi','state_id' => '17','country_id' => '1','status' => '1'),
            array('title' => 'South West Delhi','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Ahmedabad','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Gandhi Nagar','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Ahmedabad City','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Banaskantha','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Bharuch','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Na','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Botab','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Mahesana','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Gandhinagar','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Patan','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Sabarkantha','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Aravalli','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Amreli','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Anand','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Bhavnagar','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Rajkot','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Jamnagar','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Devbhoomi Dwerka','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Morbi','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Gir Somnath','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Junagadh','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Diu','state_id' => '18','country_id' => '1','status' => '1'),
            array('title' => 'Kachchh','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Porbandar','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Surendra Nagar','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Kheda','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Mahisagar','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Surat','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Tapi','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Dangs','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Narmada','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Navsari','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Dahod','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Panch Mahals','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Vadodara','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Chhotaudepur','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Chhota Udepur','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Valsad','state_id' => '7','country_id' => '1','status' => '1'),
            array('title' => 'Dadra  nagar Haveli','state_id' => '19','country_id' => '1','status' => '1'),
            array('title' => 'Daman','state_id' => '18','country_id' => '1','status' => '1'),
            array('title' => 'Ambala','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Yamunanagar','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Panchkula','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Ambala City','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Bhiwani','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Bhiwani','state_id' => '10','country_id' => '1','status' => '1'),
            array('title' => 'Faridabad','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Palwal','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Mewat','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Rewari','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Gurgaon','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Mahendragarh','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Fatehabad','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Sirsa','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Hisar','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Karnal','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Panipat','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Jind','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Kurukshetra','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Kaithal','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Jhajjar','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Rohtak','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Jhajjar','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Jhajjar','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Jhajjar','state_id' => '20','country_id' => '1','status' => '1'),
            array('title' => 'Jhajjar','state_id' => '21','country_id' => '1','status' => '1'),
            array('title' => 'Jhajjar','state_id' => '22','country_id' => '1','status' => '1'),
            array('title' => 'Jhajjar','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Jhajjar','state_id' => '10','country_id' => '1','status' => '1'),
            array('title' => 'Jhajjar','state_id' => '23','country_id' => '1','status' => '1'),
            array('title' => 'Jhajjar','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Rohtak','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Jhajjar','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Jhajjar','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Jhajjar','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Jhajjar','state_id' => '27','country_id' => '1','status' => '1'),
            array('title' => 'Jhajjar','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Jhajjar','state_id' => '29','country_id' => '1','status' => '1'),
            array('title' => 'Jhajjar','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Sonipat','state_id' => '9','country_id' => '1','status' => '1'),
            array('title' => 'Chamba','state_id' => '10','country_id' => '1','status' => '1'),
            array('title' => 'Kangra','state_id' => '10','country_id' => '1','status' => '1'),
            array('title' => 'Hamirpurhp','state_id' => '10','country_id' => '1','status' => '1'),
            array('title' => 'Na','state_id' => '10','country_id' => '1','status' => '1'),
            array('title' => 'Bilaspur Hp','state_id' => '10','country_id' => '1','status' => '1'),
            array('title' => 'Hamirpur(hp)','state_id' => '10','country_id' => '1','status' => '1'),
            array('title' => 'Bilaspur (hp)','state_id' => '10','country_id' => '1','status' => '1'),
            array('title' => 'Mandi','state_id' => '10','country_id' => '1','status' => '1'),
            array('title' => 'Kullu','state_id' => '10','country_id' => '1','status' => '1'),
            array('title' => 'Lahul  spiti','state_id' => '10','country_id' => '1','status' => '1'),
            array('title' => 'Kinnaur','state_id' => '10','country_id' => '1','status' => '1'),
            array('title' => 'Shimla','state_id' => '10','country_id' => '1','status' => '1'),
            array('title' => 'Sirmaur','state_id' => '10','country_id' => '1','status' => '1'),
            array('title' => 'Solan','state_id' => '10','country_id' => '1','status' => '1'),
            array('title' => 'Una','state_id' => '10','country_id' => '1','status' => '1'),
            array('title' => 'Bandipur','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Kupwara','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Baramulla','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Kulgam','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Samba','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Jammu','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Kathua','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Poonch','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Kargil','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Rajauri','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Pulwama','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Budgam','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Srinagar','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Ananthnag','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Ganderbal','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Shopian','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Reasi','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Doda','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Ramban','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Udhampur','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Leh','state_id' => '11','country_id' => '1','status' => '1'),
            array('title' => 'Dhanbad','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Bokaro','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Giridh','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Hazaribag','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Chatra','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Ramgarh','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Koderma','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Hazaribagh','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Koderma','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Palamau','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Hazaribag','state_id' => '31','country_id' => '1','status' => '1'),
            array('title' => 'Gumla','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Latehar','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Garhwa','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Pakur','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Ranchi','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Simdega','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Lohardaga','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Khunti','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'West Singhbhum','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Godda','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Jamtara','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Sahibganj','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Deoghar','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Dumka','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Seraikelakharsawan','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'East Singhbhum','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Shopian','state_id' => '30','country_id' => '1','status' => '1'),
            array('title' => 'Bengaluru','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Bangalore','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Bengaluru Rural','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Ramanagar','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Ramdurg','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Ramanagara','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Bagalkot','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Bellary','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Davangere','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Ballari','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Belagavi','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Bidar','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Belgaum','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Hubballi','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Dharwad','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Madikeri','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Arsikere','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Kundgol','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Kalghatgi','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Gadag','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Koppal','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Haveri','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Kalaburagi','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Yadgir','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Gulbarga','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Uttara Kannada','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Raichur','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Siddapur','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Joida','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Bijapur(kar)','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Bijapur','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Chickmagalur','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Chikkamagaluru','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Chitradurga','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Hassan','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Kodagu','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Athani','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Jamkhandi','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Kollegal','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Chikkaballapur','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Kolar','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Mandya','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Dakshina Kannada','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Udupi','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Mysuru','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Saraswathipuram','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Hanagodu','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Mysore','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Hunsur','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Chamrajnagar','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Bailhongal','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Nanjangud','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Kollegal','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Sagar','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Chamarajanagar','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Shivamogga','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Tumakuru','state_id' => '13','country_id' => '1','status' => '1'),
            array('title' => 'Kollam','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Pathanamthitta','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Alappuzha','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Thiruvananthapuram','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Wayanad','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Kozhikode','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Malappuram','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Kannur','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Kasargod','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Kasaragod','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Palakkad','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Thalassery','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Malappurm','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Mahe','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Ernakulam','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Kottayam','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Idukki','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Thrissur','state_id' => '14','country_id' => '1','status' => '1'),
            array('title' => 'Lakshadweep','state_id' => '32','country_id' => '1','status' => '1'),
            array('title' => 'Kochi','state_id' => '32','country_id' => '1','status' => '1'),
            array('title' => 'Seoni','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Balaghat','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Bhopal','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Raisen','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Chhatarpur','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Tikamgarh','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Panna','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Chhindwara','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Betul','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Hoshangabad','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Harda','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Narsinghpur','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Sehore','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Satna','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Rewa','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Damoh','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Sagar','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Datia','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Anuppur','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Umaria','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Shahdol','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Sidhi','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Singrauli','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Vidisha','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Ashok Nagar','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Shivpuri','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Guna','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Gwalior','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Indore','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Dewas','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Dhar','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Katni','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Jabalpur','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Khandwa','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Khargone','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Barwani','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Burhanpur','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Neemuch','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Mandsaur','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Bhind','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Morena','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Sheopur','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Agar Malwa','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Ratlam','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Jhabua','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Alirajpur','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Rajgarh','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Ujjain','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Shajapur','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Mandla','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Dindori','state_id' => '12','country_id' => '1','status' => '1'),
            array('title' => 'Jalna','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Aurangabad','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Beed','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Jalgaon','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Bhusawal','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Dhule','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Nandurbar','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Jalgoan','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Nanded','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Latur','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Osmanabad','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Hingoli','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Parbhani','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'South Goa','state_id' => '8','country_id' => '1','status' => '1'),
            array('title' => 'North Goa','state_id' => '8','country_id' => '1','status' => '1'),
            array('title' => 'Kolhapur','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Ratnagiri','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Raigarh(mh)','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Sangli','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Miraj','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Sindhudurg','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Mumbai','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Mumbai Subueban','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Akola','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Washim','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Amravati','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Buldhana','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Gadchiroli','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Chandrapur','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Nagpur','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Gondia','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Bhandara','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Wardha','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Yavatmal','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Malegaon','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Na','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Nashik','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Thane','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Raigarh(mh)','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Palghar','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Raigarh','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Ahmed Nagar','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Solapur','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Pune','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Satara','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Shrirampur','state_id' => '15','country_id' => '1','status' => '1'),
            array('title' => 'Imphal West','state_id' => '20','country_id' => '1','status' => '1'),
            array('title' => 'Churachandpur','state_id' => '20','country_id' => '1','status' => '1'),
            array('title' => 'Thoubal','state_id' => '20','country_id' => '1','status' => '1'),
            array('title' => 'Ukhrul','state_id' => '20','country_id' => '1','status' => '1'),
            array('title' => 'Tamenglong','state_id' => '20','country_id' => '1','status' => '1'),
            array('title' => 'Chandel','state_id' => '20','country_id' => '1','status' => '1'),
            array('title' => 'Imphal East','state_id' => '20','country_id' => '1','status' => '1'),
            array('title' => 'Bishnupur','state_id' => '20','country_id' => '1','status' => '1'),
            array('title' => 'Senapati','state_id' => '20','country_id' => '1','status' => '1'),
            array('title' => 'Na','state_id' => '20','country_id' => '1','status' => '1'),
            array('title' => 'Tengnoupal','state_id' => '20','country_id' => '1','status' => '1'),
            array('title' => 'Imphal','state_id' => '20','country_id' => '1','status' => '1'),
            array('title' => 'Jiribam','state_id' => '20','country_id' => '1','status' => '1'),
            array('title' => 'Thanlon','state_id' => '20','country_id' => '1','status' => '1'),
            array('title' => 'Aizawl','state_id' => '22','country_id' => '1','status' => '1'),
            array('title' => 'Mammit','state_id' => '22','country_id' => '1','status' => '1'),
            array('title' => 'Lunglei','state_id' => '22','country_id' => '1','status' => '1'),
            array('title' => 'Kolasib','state_id' => '22','country_id' => '1','status' => '1'),
            array('title' => 'Lawngtlai','state_id' => '22','country_id' => '1','status' => '1'),
            array('title' => 'Na','state_id' => '22','country_id' => '1','status' => '1'),
            array('title' => 'Champhai','state_id' => '22','country_id' => '1','status' => '1'),
            array('title' => 'Saiha','state_id' => '22','country_id' => '1','status' => '1'),
            array('title' => 'Serchhip','state_id' => '22','country_id' => '1','status' => '1'),
            array('title' => 'Aizawal','state_id' => '22','country_id' => '1','status' => '1'),
            array('title' => 'Mamit','state_id' => '22','country_id' => '1','status' => '1'),
            array('title' => 'Zunhebotto','state_id' => '23','country_id' => '1','status' => '1'),
            array('title' => 'Dimapur','state_id' => '23','country_id' => '1','status' => '1'),
            array('title' => 'Wokha','state_id' => '23','country_id' => '1','status' => '1'),
            array('title' => 'Phek','state_id' => '23','country_id' => '1','status' => '1'),
            array('title' => 'Zunheboto','state_id' => '23','country_id' => '1','status' => '1'),
            array('title' => 'Mokokchung','state_id' => '23','country_id' => '1','status' => '1'),
            array('title' => 'Kiphire','state_id' => '23','country_id' => '1','status' => '1'),
            array('title' => 'Tuensang','state_id' => '23','country_id' => '1','status' => '1'),
            array('title' => 'Mon','state_id' => '23','country_id' => '1','status' => '1'),
            array('title' => 'Kohima','state_id' => '23','country_id' => '1','status' => '1'),
            array('title' => 'Peren','state_id' => '23','country_id' => '1','status' => '1'),
            array('title' => 'Longleng','state_id' => '23','country_id' => '1','status' => '1'),
            array('title' => 'Na','state_id' => '23','country_id' => '1','status' => '1'),
            array('title' => 'Dimapur','state_id' => '27','country_id' => '1','status' => '1'),
            array('title' => 'South Tripura','state_id' => '29','country_id' => '1','status' => '1'),
            array('title' => 'West Tripura','state_id' => '29','country_id' => '1','status' => '1'),
            array('title' => 'West Tripura','state_id' => '22','country_id' => '1','status' => '1'),
            array('title' => 'Gomati','state_id' => '29','country_id' => '1','status' => '1'),
            array('title' => 'Na','state_id' => '29','country_id' => '1','status' => '1'),
            array('title' => 'Sepahijala','state_id' => '29','country_id' => '1','status' => '1'),
            array('title' => 'Agartala?','state_id' => '29','country_id' => '1','status' => '1'),
            array('title' => 'West Tripura','state_id' => '20','country_id' => '1','status' => '1'),
            array('title' => 'Gomti','state_id' => '29','country_id' => '1','status' => '1'),
            array('title' => 'Lower Dibang Valley','state_id' => '2','country_id' => '1','status' => '1'),
            array('title' => 'East Siang','state_id' => '2','country_id' => '1','status' => '1'),
            array('title' => 'Dibang Valley','state_id' => '2','country_id' => '1','status' => '1'),
            array('title' => 'West Siang','state_id' => '2','country_id' => '1','status' => '1'),
            array('title' => 'Lohit','state_id' => '2','country_id' => '1','status' => '1'),
            array('title' => 'Papum Pare','state_id' => '2','country_id' => '1','status' => '1'),
            array('title' => 'Tawang','state_id' => '2','country_id' => '1','status' => '1'),
            array('title' => 'West Kameng','state_id' => '2','country_id' => '1','status' => '1'),
            array('title' => 'East Kameng','state_id' => '2','country_id' => '1','status' => '1'),
            array('title' => 'Lower Subansiri','state_id' => '2','country_id' => '1','status' => '1'),
            array('title' => 'Changlang','state_id' => '2','country_id' => '1','status' => '1'),
            array('title' => 'Tirap','state_id' => '2','country_id' => '1','status' => '1'),
            array('title' => 'Kurung Kumey','state_id' => '2','country_id' => '1','status' => '1'),
            array('title' => 'Upper Siang','state_id' => '2','country_id' => '1','status' => '1'),
            array('title' => 'Upper Subansiri','state_id' => '2','country_id' => '1','status' => '1'),
            array('title' => 'Upper Dibang Valley','state_id' => '2','country_id' => '1','status' => '1'),
            array('title' => 'Na','state_id' => '2','country_id' => '1','status' => '1'),
            array('title' => 'Dhalai','state_id' => '29','country_id' => '1','status' => '1'),
            array('title' => 'North Tripura','state_id' => '29','country_id' => '1','status' => '1'),
            array('title' => 'Khowai','state_id' => '29','country_id' => '1','status' => '1'),
            array('title' => 'Dharmanagar','state_id' => '29','country_id' => '1','status' => '1'),
            array('title' => 'West Garo Hills','state_id' => '21','country_id' => '1','status' => '1'),
            array('title' => 'Jaintia Hills','state_id' => '21','country_id' => '1','status' => '1'),
            array('title' => 'Na','state_id' => '21','country_id' => '1','status' => '1'),
            array('title' => 'East Khasi Hills','state_id' => '21','country_id' => '1','status' => '1'),
            array('title' => 'South Garo Hills','state_id' => '21','country_id' => '1','status' => '1'),
            array('title' => 'East Garo Hills','state_id' => '21','country_id' => '1','status' => '1'),
            array('title' => 'Ri Bhoi','state_id' => '21','country_id' => '1','status' => '1'),
            array('title' => 'Shillong','state_id' => '21','country_id' => '1','status' => '1'),
            array('title' => 'West Khasi Hills','state_id' => '21','country_id' => '1','status' => '1'),
            array('title' => 'Tura','state_id' => '21','country_id' => '1','status' => '1'),
            array('title' => 'West Jaintia Hills','state_id' => '21','country_id' => '1','status' => '1'),
            array('title' => 'South West Khasi Hills','state_id' => '21','country_id' => '1','status' => '1'),
            array('title' => 'East Jaintia Hills','state_id' => '21','country_id' => '1','status' => '1'),
            array('title' => 'Khorda','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Baleswar','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Balasore','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Bhadrak','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Kendujhar','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Cuttack','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Jajapur','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Kendrapara','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Jagatsinghapur','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Mayurbhanj','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Nabarangapur','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Puri','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Nayagarh','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Ganjam','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Kandhamal','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Gajapati','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Kalahandi','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Nuapada','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Koraput','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Malkangiri','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Rayagada','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Boudh','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Balangir','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Sonapur','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Angul','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Dhenkanal','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Sambalpur','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Bargarh','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Jharsuguda','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Debagarh','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Sundergarh','state_id' => '24','country_id' => '1','status' => '1'),
            array('title' => 'Ropar','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Chandighar','state_id' => '33','country_id' => '1','status' => '1'),
            array('title' => 'Chandighar','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Mohali','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Rupnagar','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Mohali','state_id' => '33','country_id' => '1','status' => '1'),
            array('title' => 'Moga','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Ludhiana','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Fatehgarh Sahib','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Patiala','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Sangrur','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Amritsar','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Tarn Taran','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Bathinda','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Mansa','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Barnala','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Muktsar','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Faridkot','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Fazilka','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Firozpur','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Ferozepur','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Pathankot','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Gurdaspur','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Hoshiarpur','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Jalandhar','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Nawanshahr','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Kapurthala','state_id' => '25','country_id' => '1','status' => '1'),
            array('title' => 'Alwar','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Banswara','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Bharatpur','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Dholpur','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Jaipur','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Dausa','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Sawai Madhopur','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Karauli','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Kota','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Ajmer','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Bhilwara','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Pratapghar','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Chittorgarh','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Pali','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Dungarpur','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Baran','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Jhalawar','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Bundi','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Tonk','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Rajsamand','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Udaipur','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Barmer','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Bikaner','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Churu','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Jhujhunu','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Jodhpur','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Jaisalmer','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Nagaur','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Sikar','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Sirohi','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Jalor','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Sri Ganganagar','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Hanumangarh','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Sriganganagar','state_id' => '26','country_id' => '1','status' => '1'),
            array('title' => 'Cuddalore','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Villupuram','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Nagapattinam','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Perambalur','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Dharmapuri','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Karur','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Tiruchirappalli','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Tiruppur','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Sivaganga','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Pudukkottai','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Dindigul','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Tiruvarur','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Thanjavur','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Karaikal','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Ariyalur','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Salem','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Vellore','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Chennai','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Tiruvannamalai','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Kanchipuram','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Tiruvallur','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Pondicherry','state_id' => '34','country_id' => '1','status' => '1'),
            array('title' => 'Pondicherry','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Villupuram','state_id' => '34','country_id' => '1','status' => '1'),
            array('title' => 'Kanyakumari','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Ramanathapuram','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Tuticorin','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Tirunelveli','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Virudhunagar','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Madurai','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Theni','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Coimbatore','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Krishnagiri','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Erode','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Namakkal','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Nilgiris','state_id' => '28','country_id' => '1','status' => '1'),
            array('title' => 'Hyderabad','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Rangareddy','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Ranga Reddy','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Rangareddy','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Siddipet','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Medak','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Karim Nagar','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Mancherial','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Sangareddy','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Zaheerabad','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Khammam','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Vikarabad','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Trimulgherry','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Nalgonda','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Secunderabad','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'K.v.rangareddy','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Adilabad','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Nirmal','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Warangal','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Parkal','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Hanamkonda','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Jangaon','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Jayashankar','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Bhupalpalli','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Sircilla','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Jagtial','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Peddapalli','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Kothagudem','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Kothagudem Colls','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Bhadrachalam','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Mahabub Nagar','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Gadwal','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Wanaparthy','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Mahabub Nagar','state_id' => '1','country_id' => '1','status' => '1'),
            array('title' => 'Bhongir','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Nizamabad','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Kamareddy','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Suryapet','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Nagar Kurnool','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Stn. Jadcherla','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Mahabubabad','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Warangal Rural','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Mahabuababad','state_id' => '3','country_id' => '1','status' => '1'),
            array('title' => 'Agra','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Agra','state_id' => '35','country_id' => '1','status' => '1'),
            array('title' => 'Aligarh','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Hathras','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Bulandshahr','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Allahabad','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Gautam Buddha Nagar','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Etah','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Kanshiram Nagar','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Etawah','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Auraiya','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Jhansi','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Jalaun','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Lalitpur','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Hapur','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Firozabad','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Mainpuri','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Faizabad','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Raebareli','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Mathura','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Kaushambi','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Prayagraj Allahabad','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Kushinagar','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Ghazipur','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Varanasi','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Sonbhadra','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Mirzapur','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Pratapgarh','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Kanpur Dehat','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Sultanpur','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Amethi','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Pilibhit','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Bareilly','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Bijnor','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Budaun','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Hardoi','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Kheri','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Meerut','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Bagpat','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Amroha','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Sambhal','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Rampur','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Moradabad','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Kanpur Nagar','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Muzaffarnagar','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Saharanpur','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Haridwar','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Shahjahanpur','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Sant Ravidas Nagar','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Azamgarh','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Mau','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Shrawasti','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Bahraich','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Siddharthnagar','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Basti','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Sant Kabir Nagar','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Basti','state_id' => '18','country_id' => '1','status' => '1'),
            array('title' => 'Siddharthnagar','state_id' => '32','country_id' => '1','status' => '1'),
            array('title' => 'Basti','state_id' => '33','country_id' => '1','status' => '1'),
            array('title' => 'Siddharthnagar','state_id' => '34','country_id' => '1','status' => '1'),
            array('title' => 'Siddharthnagar','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'Siddharthnagar','state_id' => '17','country_id' => '1','status' => '1'),
            array('title' => 'Basti','state_id' => '19','country_id' => '1','status' => '1'),
            array('title' => 'Basti','state_id' => '35','country_id' => '1','status' => '1'),
            array('title' => 'Deoria','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Gonda','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Balrampur','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Gorakhpur','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Maharajganj','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Mahrajganj','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Banda','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Chitrakoot','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Mahoba','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Hamirpur','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Kannauj','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Farrukhabad','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Fatehpur','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Unnao','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Barabanki','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Ambedkar Nagar','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Ghaziabad','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Lucknow','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Sitapur','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Ballia','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Ballia','state_id' => '5','country_id' => '1','status' => '1'),
            array('title' => 'Jaunpur','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Chandauli','state_id' => '6','country_id' => '1','status' => '1'),
            array('title' => 'Almora','state_id' => '31','country_id' => '1','status' => '1'),
            array('title' => 'Bageshwar','state_id' => '31','country_id' => '1','status' => '1'),
            array('title' => 'Chamoli','state_id' => '31','country_id' => '1','status' => '1'),
            array('title' => 'Rudraprayag','state_id' => '31','country_id' => '1','status' => '1'),
            array('title' => 'Haridwar','state_id' => '31','country_id' => '1','status' => '1'),
            array('title' => 'Dehradun','state_id' => '31','country_id' => '1','status' => '1'),
            array('title' => 'Nainital','state_id' => '31','country_id' => '1','status' => '1'),
            array('title' => 'Champawat','state_id' => '31','country_id' => '1','status' => '1'),
            array('title' => 'Udham Singh Nagar','state_id' => '31','country_id' => '1','status' => '1'),
            array('title' => 'Pauri Garhwal','state_id' => '31','country_id' => '1','status' => '1'),
            array('title' => 'Pithoragarh','state_id' => '31','country_id' => '1','status' => '1'),
            array('title' => 'Tehri Garhwal','state_id' => '31','country_id' => '1','status' => '1'),
            array('title' => 'Uttarkashi','state_id' => '31','country_id' => '1','status' => '1'),
            array('title' => 'East Sikkim','state_id' => '27','country_id' => '1','status' => '1'),
            array('title' => 'West Sikkim','state_id' => '27','country_id' => '1','status' => '1'),
            array('title' => 'South Sikkim','state_id' => '27','country_id' => '1','status' => '1'),
            array('title' => 'East Sikkim','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'North Sikkim','state_id' => '27','country_id' => '1','status' => '1'),
            array('title' => 'North Sikkim','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'South Sikkim','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'South Andaman','state_id' => '35','country_id' => '1','status' => '1'),
            array('title' => 'North And Middle Andaman','state_id' => '35','country_id' => '1','status' => '1'),
            array('title' => 'Nicobar','state_id' => '35','country_id' => '1','status' => '1'),
            array('title' => 'Port Blair','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'North & Middle Andaman','state_id' => '35','country_id' => '1','status' => '1'),
            array('title' => 'Kolkata','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'North 24 Parganas','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'Birbhum','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'South 24 Parganas','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'Murshidabad','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'Medinipur','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'Nadia','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'Kolkata','state_id' => '35','country_id' => '1','status' => '1'),
            array('title' => 'Cooch Behar','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'Jalpaiguri','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'Darjiling','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'East Midnapore','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'Darjeeling','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'Kalimpong','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'West Midnapore','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'South Dinajpur','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'North Dinajpur','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'Malda','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'Bardhaman','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'Paschim Bardhaman','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'Bankura','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'Hooghly','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'Howrah','state_id' => '36','country_id' => '1','status' => '1'),
            array('title' => 'Puruliya','state_id' => '36','country_id' => '1','status' => '1')
          );
        DB::table('districts')->insert($data);
    }
}
